services:
  caddy:
    image: 'caddy:latest'
    volumes:
      - ./provision/caddy/:/etc/caddy/
      #      - ./provision/caddy/tls:/etc/ssl/private
      - ./:/var/www/app
    ports:
      - '127.0.0.1:${APP_PORT:-80}:80'
  pgsql:
    image: 'postgres:16.2'
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${DB_USERNAME:-root}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-root}'
      POSTGRES_DB: '${DB_DATABASE:-laravel}'
    volumes:
      - pgsqlmount:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:${FORWARD_DB_PORT:-5432}:5432'
  php:
    build:
      context: .
      dockerfile: './provision/docker_php'
    restart: unless-stopped
    environment:
        PHPSTAN_PRO_WEB_PORT: 11111
    ports:
        - "127.0.0.1:11111:11111"
        - "127.0.0.1:${REVERB_PORT:-8080}:8080"
    volumes:
      - ./:/var/www/app
      - ./provision/imagick.xml:/etc/ImageMagick-6/policy.xml
  redis:
    image: 'redis:7.2.4-alpine'
    command: redis-server
    restart: unless-stopped
    ports:
      - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - redismount:/data
    sysctls:
      net.core.somaxconn: '2048'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      start_period: 0s
  typesense:
      image: typesense/typesense:27.1
      restart: on-failure
      ports:
          - "127.0.0.1:${TYPESENSE_PORT:-8108}:8108"
      volumes:
          - typesensemount:/data
      command: "--data-dir /data --api-key=${TYPESENSE_KEY:-xyz} --enable-cors"
  mail:
    image: 'mailhog/mailhog:latest'
    ports:
      - '127.0.0.1:${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '127.0.0.1:${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
volumes:
  pgsqlmount:
  redismount:
  typesensemount:
